anykernel3: update anykernel3 configs

diff --git a/AnyKernel3/META-INF/com/google/android/update-binary b/AnyKernel3/META-INF/com/google/android/update-binary
--- a/AnyKernel3/META-INF/com/google/android/update-binary
+++ b/AnyKernel3/META-INF/com/google/android/update-binary
@@ -58,7 +58,7 @@ mount_apex() {
   setup_mountpoint /apex;
   mount -t tmpfs tmpfs /apex -o mode=755 && touch /apex/apextmp;
   shcon=$(cat /proc/self/attr/current);
-  echo "u:r:su:s0" > /proc/self/attr/current; # work around LOS Recovery not allowing loop mounts in recovery context
+  echo "u:r:su:s0" > /proc/self/attr/current 2>/dev/null; # work around LOS Recovery not allowing loop mounts in recovery context
   minorx=1;
   [ -e /dev/block/loop1 ] && minorx=$(ls -l /dev/block/loop1 | awk '{ print $6 }');
   num=0;
@@ -94,7 +94,7 @@ mount_apex() {
       *) mount -o bind $apex $dest && echo "$dest (bind)" >&2;;
     esac;
   done;
-  echo "$shcon" > /proc/self/attr/current;
+  echo "$shcon" > /proc/self/attr/current 2>/dev/null;
   for var in $(grep -o 'export .* /.*' /system_root/init.environ.rc | awk '{ print $2 }'); do
     eval OLD_${var}=\$$var;
   done;
@@ -369,6 +369,29 @@ do_levelcheck() {
     abort " " "Unsupported Android security patch level. Aborting...";
   fi;
 }
+do_vendorlevelcheck() {
+  [ "$(file_getprop anykernel.sh supported.vendorpatchlevels)" ] || return 1;
+  local vendor_lvl hi_lvl lo_lvl parsed_lvl supported_lvl;
+  ui_print "Checking Vendor security patch level...";
+  supported_lvl=$(file_getprop anykernel.sh supported.vendorpatchlevels | grep -oE '[0-9]{4}-[0-9]{2}|-');
+  vendor_lvl=$(file_getprop /vendor/build.prop ro.vendor.build.security_patch);
+  parsed_lvl=$(echo $vendor_lvl | grep -oE '[0-9]{4}-[0-9]{2}');
+  if echo $supported_lvl | grep -q '^\-'; then
+    lo_lvl=0000-00;
+    hi_lvl=$(echo $supported_lvl | awk '{ print $2 }');
+  elif echo $supported_lvl | grep -q ' - '; then
+    lo_lvl=$(echo $supported_lvl | awk '{ print $1 }');
+    hi_lvl=$(echo $supported_lvl | awk '{ print $3 }');
+  elif echo $supported_lvl | grep -q '\-$'; then
+    lo_lvl=$(echo $supported_lvl | awk '{ print $1 }');
+    hi_lvl=9999-99;
+  fi;
+  if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | sort -g | grep -n "$parsed_lvl" | grep -q '^2:'; then
+    ui_print "$vendor_lvl" " ";
+  else
+    abort " " "Unsupported Vendor security patch level. Aborting...";
+  fi;
+}
 dump_moduleinfo() {
 cat <<EOF > $1;
 id=ak3-helper
@@ -440,7 +463,7 @@ do_modules() {
       cp -f $AKHOME/vertmp $moddir/version;
       touch $moddir/update;
       umask $umask;
-      chcon -hR "u:object_r:system_file:s0" $moddir;
+      /system/bin/chcon -hR "u:object_r:system_file:s0" $moddir;
       [ "$umountksu" ] && umount /data/adb/modules_update;
     else
       ui_print "Magisk/KernelSU installation not found. Skipped!";
@@ -477,7 +500,7 @@ do_modules() {
       chown 0:0 $modtarget;
       chmod 644 $modtarget;
       if [ "$modcon" ]; then
-        chcon "u:object_r:${modcon}_file:s0" $modtarget;
+        /system/bin/chcon "u:object_r:${modcon}_file:s0" $modtarget;
       fi;
       if is_mounted $modtarget; then
         mount -o ro,remount -t auto $modtarget;
@@ -529,6 +552,7 @@ setup_env;
 do_devicecheck;
 do_versioncheck;
 do_levelcheck;
+do_vendorlevelcheck;
 
 ui_print "Installing...";
 # hack to maintain support for anykernel.sh files that weren't updated correctly along with the AK core
